import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  fixedBackground: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(180deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    zIndex: 0,
  },
  container: {
    position: 'relative',
    zIndex: 1,
    minHeight: '100dvh',
    padding: '20px',
    fontFamily: "'Cinzel', 'Georgia', serif",
    color: '#f4e4bc',
  },
  header: {
    textAlign: 'center',
    marginBottom: '30px',
    paddingTop: '20px',
    position: 'relative',
    zIndex: 1,
  },
  skull: {
    fontSize: '64px',
    animation: 'bob 2s ease-in-out infinite',
    textShadow: '0 0 30px rgba(255,215,0,0.5)',
  },
  title: {
    fontSize: '42px',
    margin: '10px 0',
    fontWeight: 'bold',
    background: 'linear-gradient(180deg, #ffd700 0%, #b8860b 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textShadow: 'none',
    letterSpacing: '3px',
  },
  subtitle: {
    fontSize: '20px',
    opacity: 0.8,
    fontStyle: 'italic',
    letterSpacing: '5px',
  },
  setupCard: {
    background: 'linear-gradient(135deg, rgba(139,69,19,0.4) 0%, rgba(101,67,33,0.6) 100%)',
    borderRadius: '20px',
    padding: '30px',
    maxWidth: '500px',
    margin: '0 auto',
    border: '2px solid #b8860b',
    boxShadow: '0 10px 40px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,215,0,0.2)',
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  cardTitle: {
    fontSize: '24px',
    textAlign: 'center',
    marginBottom: '10px',
    color: '#ffd700',
  },
  hint: {
    textAlign: 'center',
    opacity: 0.7,
    marginBottom: '20px',
    fontSize: '14px',
  },
  inputRow: {
    display: 'flex',
    gap: '10px',
    marginBottom: '20px',
    alignItems: 'stretch',
    width: '100%',
    boxSizing: 'border-box',
  },
  input: {
    flex: 1,
    padding: '15px',
    fontSize: '18px',
    border: '2px solid #b8860b',
    borderRadius: '10px',
    background: 'rgba(0,0,0,0.3)',
    color: '#f4e4bc',
    outline: 'none',
    fontFamily: 'inherit',
    minWidth: 0,
    boxSizing: 'border-box',
  },
  addBtn: {
    width: '54px',
    fontSize: '24px',
    border: '2px solid #b8860b',
    borderRadius: '10px',
    background: 'linear-gradient(180deg, #b8860b 0%, #8b4513 100%)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 'bold',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  playerList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginBottom: '20px',
  },
  playerChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 15px',
    background: 'rgba(0,0,0,0.3)',
    borderRadius: '30px',
    border: '1px solid #b8860b',
  },
  playerIcon: {
    fontSize: '18px',
  },
  removeBtn: {
    background: 'transparent',
    border: 'none',
    color: '#ff4136',
    fontSize: '20px',
    cursor: 'pointer',
    padding: '0 5px',
  },
  startBtn: {
    width: '100%',
    padding: '18px',
    fontSize: '20px',
    border: 'none',
    borderRadius: '15px',
    background: 'linear-gradient(180deg, #2ecc40 0%, #1a8a2a 100%)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontFamily: 'inherit',
    letterSpacing: '2px',
    boxShadow: '0 5px 20px rgba(46,204,64,0.4)',
    marginTop: '10px',
  },
  clearBtn: {
    padding: '10px 20px',
    fontSize: '14px',
    border: '1px solid #ff4136',
    borderRadius: '10px',
    background: 'transparent',
    color: '#ff4136',
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginBottom: '10px',
  },
  endGameBtn: {
    padding: '8px 16px',
    fontSize: '12px',
    border: '1px solid rgba(255,65,54,0.5)',
    borderRadius: '8px',
    background: 'rgba(255,65,54,0.1)',
    color: '#ff4136',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  undoBtn: {
    padding: '8px 16px',
    fontSize: '12px',
    border: '1px solid rgba(255,215,0,0.5)',
    borderRadius: '8px',
    background: 'rgba(255,215,0,0.1)',
    color: '#ffd700',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  historyBtn: {
    padding: '8px 16px',
    fontSize: '12px',
    border: '1px solid rgba(46,204,64,0.5)',
    borderRadius: '8px',
    background: 'rgba(46,204,64,0.1)',
    color: '#2ecc40',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  helpBtn: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    width: '40px',
    height: '40px',
    fontSize: '20px',
    fontWeight: 'bold',
    border: '2px solid #b8860b',
    borderRadius: '50%',
    background: 'rgba(0,0,0,0.3)',
    color: '#ffd700',
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    zIndex: 10,
  },
  cancelBtn: {
    padding: '8px 16px',
    fontSize: '12px',
    border: '1px solid rgba(255,215,0,0.5)',
    borderRadius: '8px',
    background: 'transparent',
    color: '#f4e4bc',
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginTop: '10px',
  },
  historyRoundCard: {
    background: 'linear-gradient(135deg, rgba(139,69,19,0.3) 0%, rgba(101,67,33,0.4) 100%)',
    borderRadius: '15px',
    padding: '15px',
    border: '1px solid rgba(184,134,11,0.5)',
  },
  historyRoundTitle: {
    fontSize: '18px',
    color: '#ffd700',
    marginBottom: '10px',
    marginTop: 0,
  },
  historyPlayerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: '1px solid rgba(255,215,0,0.1)',
  },
  historyPlayerName: {
    fontSize: '16px',
    fontWeight: 'bold',
  },
  historyDetails: {
    display: 'flex',
    gap: '10px',
    fontSize: '14px',
  },
  roundHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    padding: '15px 20px',
    background: 'rgba(0,0,0,0.3)',
    borderRadius: '15px',
    border: '1px solid #b8860b',
  },
  roundBadge: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#ffd700',
  },
  cardsInfo: {
    fontSize: '14px',
    opacity: 0.8,
  },
  phaseTitle: {
    fontSize: '28px',
    textAlign: 'center',
    marginBottom: '10px',
    color: '#ffd700',
  },
  phaseHint: {
    textAlign: 'center',
    opacity: 0.7,
    marginBottom: '25px',
    fontSize: '16px',
  },
  playersGrid: {
    display: 'grid',
    gap: '15px',
    marginBottom: '20px',
  },
  playerCard: {
    background: 'linear-gradient(135deg, rgba(139,69,19,0.4) 0%, rgba(101,67,33,0.5) 100%)',
    borderRadius: '15px',
    padding: '20px',
    border: '1px solid #b8860b',
  },
  playerName: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '5px',
  },
  totalScore: {
    fontSize: '14px',
    opacity: 0.7,
    marginBottom: '15px',
  },
  bidSection: {
    marginTop: '15px',
  },
  bidLabel: {
    display: 'block',
    fontSize: '14px',
    marginBottom: '10px',
    opacity: 0.8,
  },
  bidButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  bidBtn: {
    width: '44px',
    height: '44px',
    fontSize: '18px',
    border: '2px solid #b8860b',
    borderRadius: '10px',
    background: 'rgba(0,0,0,0.3)',
    color: '#f4e4bc',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.2s',
  },
  bidBtnActive: {
    background: 'linear-gradient(180deg, #ffd700 0%, #b8860b 100%)',
    color: '#1a1a2e',
    fontWeight: 'bold',
    transform: 'scale(1.1)',
  },
  bidDisplay: {
    fontSize: '16px',
    padding: '8px 15px',
    background: 'rgba(255,215,0,0.2)',
    borderRadius: '8px',
    display: 'inline-block',
    marginBottom: '15px',
  },
  stepper: {
    marginBottom: '15px',
  },
  stepperLabel: {
    display: 'block',
    fontSize: '14px',
    marginBottom: '8px',
    opacity: 0.8,
  },
  stepperControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  stepperBtn: {
    width: '50px',
    height: '50px',
    fontSize: '28px',
    border: '2px solid #b8860b',
    borderRadius: '12px',
    background: 'linear-gradient(180deg, #b8860b 0%, #8b4513 100%)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  stepperValue: {
    fontSize: '32px',
    fontWeight: 'bold',
    minWidth: '50px',
    textAlign: 'center',
  },
  bonusSection: {
    marginTop: '15px',
    padding: '15px',
    background: 'rgba(255,215,0,0.1)',
    borderRadius: '10px',
    border: '1px dashed #ffd700',
  },
  bonusTitle: {
    fontSize: '16px',
    marginBottom: '15px',
    color: '#ffd700',
  },
  bonusToggle: {
    width: '100%',
    padding: '12px',
    fontSize: '14px',
    border: '2px solid #b8860b',
    borderRadius: '10px',
    background: 'rgba(0,0,0,0.3)',
    color: '#f4e4bc',
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginTop: '10px',
    transition: 'all 0.2s',
  },
  bonusToggleActive: {
    background: 'linear-gradient(180deg, #9b59b6 0%, #6c3483 100%)',
    borderColor: '#9b59b6',
  },
  roundScore: {
    fontSize: '24px',
    fontWeight: 'bold',
    textAlign: 'right',
    marginTop: '15px',
    padding: '10px',
    background: 'rgba(0,0,0,0.2)',
    borderRadius: '8px',
  },
  actionBtn: {
    width: '100%',
    padding: '18px',
    fontSize: '20px',
    border: 'none',
    borderRadius: '15px',
    background: 'linear-gradient(180deg, #ff851b 0%, #e65c00 100%)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontFamily: 'inherit',
    letterSpacing: '2px',
    boxShadow: '0 5px 20px rgba(255,133,27,0.4)',
    marginTop: '10px',
  },
  resultsCard: {
    background: 'linear-gradient(135deg, rgba(139,69,19,0.4) 0%, rgba(101,67,33,0.6) 100%)',
    borderRadius: '20px',
    padding: '30px',
    maxWidth: '500px',
    margin: '0 auto',
    border: '2px solid #b8860b',
    boxShadow: '0 10px 40px rgba(0,0,0,0.5)',
  },
  resultRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '15px',
    borderRadius: '10px',
    marginBottom: '10px',
  },
  rank: {
    fontSize: '24px',
    marginRight: '15px',
    minWidth: '40px',
  },
  resultName: {
    flex: 1,
    fontSize: '20px',
  },
  resultScore: {
    fontSize: '24px',
    fontWeight: 'bold',
  },
};

// Inject global styles
const styleSheet = document.createElement('style');
styleSheet.textContent = `
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap');

  @keyframes bob {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-10px); }
  }

  * { box-sizing: border-box; }

  html, body {
    margin: 0;
    padding: 0;
    background: #1a1a2e;
    min-height: 100vh;
  }
`;
document.head.appendChild(styleSheet);
